name: Continuous Integration

on:
  push:
    branches: ["**"]

jobs:
  tests-api:
    name: "Tests API"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./assistify-api

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install hatch
          hatch env create
      - name: Unit tests
        run: |
          hatch run test
